apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dev1
namespace: dev1

helmGlobals:
  chartHome: charts

helmCharts:
- name: helmchart-app
  releaseName: app-v1
  valuesFile: charts/helmchart-app/values.yaml


#helmCharts:
#- name: helmchart-app
#  includeCRDs: true
#  valuesInline:
#    replicas: 1
#  releaseName: helmchart-app
#  version: 0.1.0
#  namespace: dev1
#  repo: https://github.com/yogithakakarla/helm-argocd-v2/tree/main/base/helm-chart-backendapp
# valuesFile: values.yaml




#helmReleases:
#- name: helmchart-app
#  includeCRDs: true
#  valuesInline:
#    replicas: 1
#  releaseName: helmchart-app
#  version: 0.1.0
#  namespace: dev1
#  repo: https://github.com/yogithakakarla/helm-argocd-v2
