#
name: projectone
namespace: argocd
#apps:
#- app1:
#    appname: app1
#    wave: 3
#    env: dev
#    server: https://kubernetes.default.svc
     
#- app2:
#    appname: app2
#    wave: 2
#    env: dev
#    server: https://kubernetes.default.svc

clusters:
  - env: dev
    server: https://kubernetes.default.svc

appOrder:
  - syncOrder: 0
    applications:
    - name: prometheus
      label: prometheus-helm
    maxUpdate: 100%
  - syncOrder: 1
    applications:
    - name: app1
      label: app1
    - name: app2
      label: app2
    maxUpdate: 100%
  - syncOrder: 2
    applications:
    - name: helmchart-backend
      label: helm-chart-backendapp
    maxUpdate: 100%
  - syncOrder: 3
    applications:
    - name: app3
      label: app3
    - name: app4
      label: app4
    - name: keda
      label: keda-helm
    maxUpdate: 100%
