#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization

#nameSuffix: -dev1
#namespace: dev1

#resources:
#- ../../../../base/helm-chart-backendapp

#patches:
#- path: patch.yaml
#  target:
#    kind: Deployment
#   name: backend


---
resources:
- ../../../../base/helm-chart-backendapp

nameSuffix: -helm-dev1
namespace: dev1
