apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dev1
namespace: dev1

#helmGlobals:
#  chartHome: ../../../../base/helm-chart-backendapp


helmCharts:
- name: helmchart-app
  includeCRDs: true
  valuesInline:
    replicas: 1
  releaseName: helmchart-app
  version: 0.1.0
  namespace: dev1
  repo: https://github.com/yogithakakarla/helm-argocd-v2
  chartPath: base/helm-chart-backendapp
