apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dev1
namespace: dev1

resources:
- ../../../../base/helm-chart-backendapp
 

#helm:
#- name: backend
#  path: ../../../../base/helm-chart-backendapp

helmGlobals:
  chartHome: ../../../../base/helm-chart-backendapp

