apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dev1
namespace: dev1

helmGlobals:
  chartHome: charts

helmCharts:
- name: helmchart-app
  releaseName: app-v1
  valuesFile: charts/helmchart-app/values.yaml
