# templates/applicationset.yaml

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-multipleapps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  {{- range $envlist := .Values.clusters }}
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/yogithakakarla/common-apps-kustomize-argocd-v2.git
              revision: HEAD
              directories:
                - path: overlays/common/{{ $envlist.env }}/bootstrap-apps/*
                - path: overlays/common/{{ $envlist.env }}/business-apps/*
                - path: overlays/{{ $envlist.env }}/*
                
          - list:
              elements:
              - envargo: {{ $envlist.env }}
                serverargo: {{ $envlist.server }}  
                apps:
                  {{- range $app := $envlist.apps }}
                  - name: {{ $app.name }}
                    maxUpdate: {{ $app.maxUpdate }}
                  {{- end }} 
  {{- end }}

  strategy:
    type: RollingSync
    rollingSync:
      steps:
      {{- range $wave := .Values.appOrder }}
        - matchExpressions:
            - key: app
              operator: In
              values:
                {{- range $app := $wave.applications }}
                {{- if hasKey $app "label" }}
                - {{ $app.label }}
                {{- else }}
                {{- if hasKey $app "name" }}
                - {{ $app.name }}
                {{- end }}
                {{- end }}
          {{- end }}
          maxUpdate: "{{ $wave.maxUpdate }}"
      {{- end }}

  template:
    metadata:
      
      name: "{{`{{.path.basename}}-{{.envargo}}`}}" 
      annotations: 
        argocd.argoproj.io/sync-options: ApplyOnly=true
      labels:
        app: "{{`{{.path.basename}}`}}"
     
    spec:
      syncPolicy:
        automated: {}
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ApplyOnly=true
          - CreateNamespace=true
      project: default
      source:
        repoURL: https://github.com/yogithakakarla/common-apps-kustomize-argocd-v2.git
        targetRevision: HEAD
        path: "{{`{{.path.path}}`}}"        
      destination:
        server: "{{`{{.serverargo}}`}}"
        namespace: "{{`{{.envargo}}`}}"
    
