# templates/applicationset.yaml

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-multipleapps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  {{- range $envlist := .Values.clusters }}
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/yogithakakarla/kustomize-multiple-apps.git
              revision: HEAD
              directories:
                - path: overlays/common/{{ $envlist.env }}/*
                - path: overlays/{{ $envlist.env }}/*
                
          - list:
              elements:
              - envargo: {{ $envlist.env }}
                serverargo: {{ $envlist.server }}   
  {{- end }}
   
  template:
    metadata:
      
      name: "{{`{{.path.basename}}-{{.envargo}}`}}" 
      annotations: 
        argocd.argoproj.io/sync-options: ApplyOnly=true
     
    spec:
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ApplyOnly=true
      project: default
      source:
        repoURL: https://github.com/yogithakakarla/kustomize-multiple-apps.git
        targetRevision: HEAD
        path: "{{`{{.path.path}}`}}"        
      destination:
        server: "{{`{{.serverargo}}`}}"
        namespace: "{{`{{.envargo}}`}}"
    
